FROM rabbitmq:3.8.9-management

#---------以下代码仅在第一次dockerfile build时执行---------
##开启GUI客户端
#RUN rabbitmq-plugins enable rabbitmq_management \
##执行脚本
#COPY ./config/rabbitmq.sh /home/rabbitmq.sh
#RUN chmod 777 /home/rabbitmq.sh
#CMD [ "./home/rabbitmq.sh" ]
#-----------------------------------------------------

